server:
  port: 9093

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


rocketmq:
  name-server: localhost:9876
  producer:
    group: rocketmq-producer-starter
    # 消息发送超时时长，默认3s
    send-message-timeout: 3000
    # 同步发送消息失败重试次数，默认2
    retry-times-when-send-failed: 3
    # 异步发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 3

base:
  swagger-package: com.github.gelald.rocketmq.producer.starter
  swagger-title: rocketmq-starter方式集成rocketmq演示
