server:
  port: 9092

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

learning:
  rocketmq:
    consumer:
      name-server-addr: localhost:9876
      consumer-switch:
        order: false
        message-model: false
        filter: false
        transaction: false
