server:
  port: 9094

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

rocketmq:
  name-server: 192.168.1.112:9876
