server:
  port: 9091

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

learning:
  rocketmq:
    producer:
      name-server-addr: localhost:9876
      producer-switch:
        order: false
        transaction: false

base:
  response-body-advice-package: ${base.swagger-package}
  swagger-package: com.github.gelald.rocketmq.producer.client.controller
  swagger-title: rocketmq-client方式集成rocketmq演示
