services:
  name-server:
    image: apache/rocketmq:5.3.4
    container_name: name-server-5
    ports:
      - "9876:9876"
    volumes:
      - ./logs:/home/rocketmq/logs
    command: sh mqnamesrv
    networks:
      - docker-internal

  broker:
    image: apache/rocketmq:5.3.4
    container_name: broker-5
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./logs:/home/rocketmq/logs
      - ./store:/home/rocketmq/store
      - ./conf/broker.conf:/home/rocketmq/rocketmq-5.3.4/conf/broker.conf
    environment:
      - JAVA_OPT_EXT=-server -Xms1g -Xmx1g -Xmn512m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m
    # 在 Local 模式下，Broker 和 Proxy 同进程部署
    command: sh mqbroker -n name-server:9876 -c /home/rocketmq/rocketmq-5.3.4/conf/broker.conf --enable-proxy
    depends_on:
      - name-server
    networks:
      - docker-internal

  dashboard:
    # arm 架构
    image: wuyb2020/built-rocketmq-dashboard:2.0.1
    # amd 架构 内部端口是 8082
    # image: wuyb2020/built-rocketmq-dashboard:2.0.0
    container_name: dashboard
    ports:
      - "18080:8080"
    entrypoint: /bin/sh -c "java $JAVA_OPTS -jar /rocketmq-dashboard.jar --rocketmq.config.isVIPChannel=false --rocketmq.config.namesrvAddrs[0]=name-server:9876"
    volumes:
      - ./tmp:/tmp
    networks:
      - docker-internal

networks:
  # 定义外部网络，命令 docker network create docker-internal
  docker-internal:
    external: true
